services:
  - type: worker
    name: welcomer-discord-bot
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: WELCOME_CHANNEL_ID
        sync: false
      - key: WELCOME_BACKGROUND_URL
        sync: false
      - key: LOG_CHANNEL_ID
        sync: false
      - key: MEMBER_ROLE_ID
        sync: false
